### ISSUE TITLE
Continuing on

### ISSUE THREAD

**Issue by donbowen** [mikebrich/sec-exhibits-ner#2]
I made a fork of the repo. Check it out, I think you'll like the updates :)

Then, we need to continue. You can dynamically update this task list:
- [x] You should update your main branch with my updates. This is done by merging my "pull request". You should have a notification for that.
- [x] Then update again to your computer via Github Desktop. Open the code and search for "todo" in the code...
- [x] Find out how to extract the subject organization in the sentence (if present) and also the verb
- [x] Modify the `ner()` function using what you just learned to do
      - to output the verb in the sentence, and subject
- [x] Tell me when you're done!

@mikebrich

**Comment by mikebrich** [comment]
Very cool - like the unpacking into the DF in the end, definitely easier to understand.  I'll work on this this week/next!
